# Docker image of centos7 with usual tools
# VERSION 1.0
# Author: huand
FROM centos:centos7
ENV WORK_PATH /usr/local
RUN yum install -y openssh-server openssh-clients telnet net-tools iptables-services vim wget less
EXPOSE 22